#!/bin/bash

set -eu

echo "Running autopep8"

docker-compose exec backend bash -c "
    find . \
      -path ./env -prune -o \
      -path ./config -prune -o \
      -path './foodsaving/*/migrations' -prune -o \
      -name '*.py' -print0 |
    xargs -0 autopep8 --in-place
  "

echo "Running autoflake"

docker-compose exec backend bash -c "
    find . \
      -path ./env -prune -o \
      -path ./config -prune -o \
      -path './foodsaving/*/migrations' -prune -o \
      -name '*.py' -print0 |
    xargs -0 autoflake -i --remove-all-unused-import
  "
